# -*- coding: utf-8 -*-
"""calculadora.py.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10HLUu4TeKsQ65OhE446H1K6jyVVPmBgE
"""

# -*- coding: utf-8 -*-
"""
Calculadora por: Pamella Mesquita
Sua função é realizar contas: somas, subtrações, multiplicação e divisão.
"""

print("--------CALCULADORA DA PAMPAM - VERSÃO:2.0 --------")
sair = False
while sair == False:

    num1 = input("Digite o primeiro número: ")
    num1 = int(num1)
    operador = input("Digite o operador(+-/*) ")
    num2 = input("Digite o segundo número: ")
    num2 = int(num2)

    # Se o operador for de SOMA: +
    if operador == "+":
        operacao = num1 + num2

    # Se o operador for SUBTRAÇÃO: -
    if operador == "-":
        operacao = num1 - num2

    # Se o operador for MULTIPLICACAO: *
    if operador == "*":
        operacao = num1 * num2

    # Se o operador for DIVISÃO: /
    if operador == "/":
        operacao = num1 / num2

    print("Resultado: ")
    print(operacao)

    Teste = input("Deseja sair? (s/n): ")
    if Teste == "s":
        sair == True